name: Sanity Check

on: [pull_request]

jobs:
  set-up-runner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: Install dependencies
        run: npm install
      - run: echo "ğŸšš All dependencies listed has been installed on the runner."
      - run: echo "ğŸ§ª Workflow will be running tests available in this branch."

  run-test:
    runs-on: ubuntu-latest
    needs: set-up-runner
    steps:
      - name: Checking pull request for test
        run: npm test:coverage
      - run: echo "ğŸ§ª Testing completes!"
      - run: echo "ğŸ“ Workflow will now run a linter check."

  run-linter:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: Checking for linter error
        run: npm lint
      - run: echo "ğŸ“ Linter check completes!"

      - run: echo "ğŸ This job has finished with status - ${{ job.status }}."
